apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cronners.notify.cronner.com
spec:
  group: notify.cronner.com
  names:
    kind: Cronner
    listKind: CronnerList
    plural: cronners
    singular: cronner
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Cronner is the Schema for the cronners API
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          description: CronnerSpec defines the desired state of Cronner
          properties:
            cluster:
              type: string
            contactMethod:
              type: string
            cronjobName:
              type: string
            currentPodID:
              type: string
            name:
              type: string
            namespace:
              type: string
            smtpDl:
              items:
                type: string
              type: array
            smtpHost:
              type: string
            smtpPort:
              format: int64
              type: integer
            smtpTls:
              type: boolean
          required:
          - cluster
          - contactMethod
          - cronjobName
          - currentPodID
          - name
          - namespace
          - smtpDl
          - smtpHost
          - smtpPort
          - smtpTls
          type: object
        status:
          description: CronnerStatus defines the observed state of Cronner
          properties:
            cluster:
              type: string
            contactMethod:
              type: string
            cronjobName:
              type: string
            currentPodID:
              type: string
            items:
              items:
                description: Cronner is the Schema for the cronners API
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  metadata:
                    type: object
                  spec:
                    description: CronnerSpec defines the desired state of Cronner
                    properties:
                      cluster:
                        type: string
                      contactMethod:
                        type: string
                      cronjobName:
                        type: string
                      currentPodID:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                      smtpDl:
                        items:
                          type: string
                        type: array
                      smtpHost:
                        type: string
                      smtpPort:
                        format: int64
                        type: integer
                      smtpTls:
                        type: boolean
                    required:
                    - cluster
                    - contactMethod
                    - cronjobName
                    - currentPodID
                    - name
                    - namespace
                    - smtpDl
                    - smtpHost
                    - smtpPort
                    - smtpTls
                    type: object
                  status: {}
                type: object
              type: array
            name:
              type: string
            namespace:
              type: string
            smtpDl:
              items:
                type: string
              type: array
            smtpHost:
              type: string
            smtpPort:
              format: int64
              type: integer
            smtpTls:
              type: boolean
          required:
          - cluster
          - contactMethod
          - cronjobName
          - currentPodID
          - items
          - name
          - namespace
          - smtpDl
          - smtpHost
          - smtpPort
          - smtpTls
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
