apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronner-operator
  namespace: cronner
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cronner-operator
  template:
    metadata:
      labels:
        name: cronner-operator
    spec:
      serviceAccountName: cronner-operator
      containers:
        - name: cronner-operator
          # Replace this with the built image name
          image: gcr.io/gd-k8s-builder/gd-cronjob-notifier:v0.0.3
          command:
          - cronner-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cronner-operator"
