kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cronner-operator
  namespace: cronner
subjects:
- kind: ServiceAccount
  name: cronner-operator
  namespace: cronner
roleRef:
  kind: ClusterRole
  name: cronner-operator
  apiGroup: rbac.authorization.k8s.io
